Lots of updates to fix some bugs and use newer deps

diff --git a/prep b/prep
--- a/prep
+++ b/prep
@@ -1,6 +1,15 @@
 #!/usr/bin/env bash
 
-clean() { rm -fr /tmp/avfinstall; }
+### Helpers begin
+err() { echo -e "${color:+\e[31m}[!] $*${color:+\e[0m}" >&2; }
+errx() { err "${*:2}"; exit "$1"; }
+good() { echo -e "${color:+\e[32m}[+] $*${color:+\e[0m}"; }
+info() { echo -e "${color:+\e[37m}[*] $*${color:+\e[0m}"; }
+subinfo() { echo -e "${color:+\e[36m}[=] $*${color:+\e[0m}"; }
+warn() { echo -e "${color:+\e[33m}[-] $*${color:+\e[0m}"; }
+### Helpers end
+
+clean() { rm -f -r "$tmp"; }
 
 usage() {
     cat <<EOF
@@ -19,6 +28,7 @@ EOF
 
 declare -a args
 unset help obfs
+tmp="/tmp/avfinstall"
 
 # Parse command line options
 while [[ $# -gt 0 ]]; do
@@ -36,57 +46,69 @@ done
 [[ -z $help ]] || usage 0
 
 # Fix repos
+info "CONVERTING TO EDGE"
 sed -i -r -e "/cdrom|v3./d" -e "s/#//g" /etc/apk/repositories
 
 # Install deps
+info "UPDATING SYSTEM"
 apk update
 apk upgrade -a -U
-apk add bash bind-tools curl dnsmasq e2fsprogs-extra \
-    findutils git grep iproute2 iptables jq libqrencode openconnect \
-    openrc openssh-server openssl openvpn sed sudo vim vimdiff \
-    wireguard-tools
+apk add bind-tools curl e2fsprogs-extra findutils grep iproute2 \
+    jq libqrencode openrc openssh-server openssl openvpn sed vim \
+    vimdiff wireguard-tools
 
-# Setup install dir
-clean
-mkdir -p /tmp/avfinstall
-cd /tmp/avfinstall
-
-# Install certifyme for OpenVPN
-git clone https://github.com/mjwhitta/certifyme.git && \
-    (cd certifyme && ./installer)
+# Install pki for OpenVPN
+info "INSTALLING PKI TOOL"
+mkdir -p "$HOME/.local/bin"
+cp ./certify "$HOME/.local/bin"
 
 # Install obfsproxy for OpenVPN
 if [[ -n $obfs ]]; then
+    subinfo "INSTALLING OBFSPROXY DEPS"
+
     # Install build deps
     apk add bzip2 gcc musl-dev py2-setuptools python2 python2-dev tar
 
+    # Setup tmp dir
+    clean
+    mkdir -p "$tmp"
+
+    # shellcheck disable=SC2164
+    pushd "$tmp"
+
     # Get pathlib
     curl -O "https://files.pythonhosted.org/packages/df/16/e9d6bcf1aed52a55bc1696324ab22586716053b3e97b85266e0f3ad36bae/pathlib2-2.3.6.tar.gz"
-    tar -f pathlib2-2.3.6.tar.gz -xz
+    tar -f pathlib2-2.3.6.tar.gz -x -z
     (cd pathlib2-2.3.6 && python2 ./setup.py install --user)
 
     # Get incremental
     curl -O "https://files.pythonhosted.org/packages/4f/c5/430765c697afc217c8491785de321a21fa4d983dda14bcd82feb965b0593/incremental-21.3.0.tar.gz"
-    tar -f incremental-21.3.0.tar.gz -xz
+    tar -f incremental-21.3.0.tar.gz -x -z
     (cd incremental-21.3.0 && python2 ./setup.py install --user)
 
     # Get idna
     curl -O "https://files.pythonhosted.org/packages/ea/b7/e0e3c1c467636186c39925827be42f16fee389dc404ac29e930e9136be70/idna-2.10.tar.gz"
-    tar -f idna-2.10.tar.gz -xz
+    tar -f idna-2.10.tar.gz -x -z
     (cd idna-2.10 && python2 ./setup.py install --user)
 
     # Get twisted
     curl -O "https://files.pythonhosted.org/packages/4a/b4/4973c7ccb5be2ec0abc779b7d5f9d5f24b17b0349e23240cfc9dc3bd83cc/Twisted-20.3.0.tar.bz2"
-    bzip2 -dk Twisted-20.3.0.tar.bz2
+    bzip2 -d -k Twisted-20.3.0.tar.bz2
     tar -f Twisted-20.3.0.tar -x
     sed -i "s/pathlib/pathlib2/g" ./Twisted-20.3.0/setup.py
     (cd Twisted-20.3.0 && python2 ./setup.py install --user)
 
     # Get obfsproxy
     curl -O "https://files.pythonhosted.org/packages/f6/25/ca704db7b8d0e462cd942ffad59674e4b2d33057c2587eab8a6b846cee1d/obfsproxy-0.2.13.tar.gz"
-    tar -f obfsproxy-0.2.13.tar.gz -xz
+    tar -f obfsproxy-0.2.13.tar.gz -x -z
     sed -i "s/pathlib/pathlib2/g" ./obfsproxy-0.2.13/setup.py
     (cd obfsproxy-0.2.13 && python2 ./setup.py install --user)
+
+    # shellcheck disable=SC2164
+    popd
+
+    # Clean up
+    clean
 
     # Uninstall build deps
     apk del -r bzip2 gcc musl-dev python2-dev tar
@@ -95,60 +117,69 @@ fi
 # Tweak some system config files
 
 ## Modules
+info "ADDING TUN MODULE"
 echo "tun" >/etc/modules-load.d/avf.conf
 
 ## Enable forwarding
+info "ENABLING IPV4 FORWARDING"
 echo "net.ipv4.ip_forward=1" >/etc/sysctl.d/avf.conf
 
 ## Update dnsmasq, if needed
-if [[ ! -e /etc/dnsmasq.d/default.conf ]]; then
-    cat >/etc/dnsmasq.d/default.conf <<EOF
+info "CONFIGURING DNSMASQ"
+apk add dnsmasq
+mkdir -p /etc/dnsmasq.d
+cat >/etc/dnsmasq.d/default.conf <<EOF
 no-resolv
-
-domain=$(grep -ioPs "^search\s+\K.+" /etc/resolv.conf)
 expand-hosts
-
-$(
-    while read -r ns; do
-        echo "server=$ns"
-    done < <(grep -ioPs "^nameserver\s+\K.+" /etc/resolv.conf)
-)
+server=8.8.8.8
 EOF
-else
-    echo "/etc/dnsmasq.d/default already exists"
-    echo "Will assume you know what you are doing..."
-fi
 rc-update add dnsmasq
 rc-service dnsmasq start
 
+## Fix /etc/resolv.conf to use dnsmasq
+info "CONFIGURING UDHCPC"
+mkdir -p /etc/udhcpc
+echo "RESOLV_CONF=no" >/etc/udhcpc/udhcpc.conf
+
+info "CONFIGURING RESOLV.CONF TO ONLY USE DNSMASQ"
+echo "nameserver 127.0.0.1" >/etc/resolv.conf
+
 ## Enable iptables
+info "CONFIGURING IPTABLES"
+apk add iptables
 rc-update add iptables
+/etc/init.d/iptables save
 rc-service iptables start
 
-## Fix /etc/resolv.conf to use dnsmasq
-mkdir -p /etc/udhcpc
-if [[ ! -e /etc/udhcpc/udhcpc.conf ]]; then
-    cat >/etc/udhcpc/udhcpc.conf <<EOF
-RESOLV_CONF=no
-EOF
-else
-    echo "/etc/udhcpc/udhcpc.conf already exists"
-    echo "Will assume you know what you are doing..."
-fi
-sed -i -r "/^nameserver/d" /etc/resolv.conf
-echo "nameserver 127.0.0.1" >>/etc/resolv.conf
+## Create default local scripts
+info "CONFIGURING DEFAULT LOCAL.D SCRIPTS"
+mkdir -p /etc/local.d
+cat >/etc/local.d/z_user.start <<EOF
+#!/usr/bin/env bash
 
-## bash setup
+export HOME="/root"
+export PATH="\$HOME/.local/bin:\$PATH"
+EOF
+chmod 755 /etc/local.d/z_user.start
+cat >/etc/local.d/z_user.stop <<EOF
+#!/usr/bin/env bash
+
+export HOME="/root"
+export PATH="\$HOME/.local/bin:\$PATH"
+EOF
+chmod 755 /etc/local.d/z_user.stop
+
+## Setup bash
+info "CONFIGURING DEFAULT SHELL (BASH)"
 sed -i -r "s/^(root:x.+)\/bin\/ash/\1\/bin\/bash/g" /etc/passwd
-echo "export PATH=/root/.local/bin:\$PATH" >>/root/.bash_profile
+grep -q -P -s "#\savf$" /root/.bash_profile || \
+    echo "export PATH=\"~/.local/bin:\$PATH\" # avf" \
+    >>/root/.bash_profile
 
 ## Make config dir
 mkdir -p /root/.config
 
-# Clean up
-cd
-clean
-
 # Reboot
-echo "You are now ready to install avf: ./installer"
-echo "You should then reboot (some services only start on boot)"
+./installer
+good "You should reboot (some services only start on boot)"
+good "Afterwards, run \"avf -h\""
